---
- name: Install php
  apt:
    name: "{{ php_packages }}"
    install_recommends: no
    state: present

- name: Enable service
  systemd:
    name: php7.3-fpm
    enabled: yes

# - name: Remove unnecessary files (default php-fpm conf)
#   file:
#     path: /etc/php/7.3/fpm/pool.d/www.conf
#     state: absent
#   notify: restart php-fpm
